### ISSUE TITLE
设计说明书5部分编写

### ISSUE THREAD

**Issue by hanhun7** [hanhun7/InsectIdentify#10]

**Comment by lemonanaaa** [comment]
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>






<p class="MsoNormal" style="margin-left:18.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1;
tab-stops:list 18.0pt"><span lang="EN-US" style="font-size:
14.0pt;mso-fareast-font-family:&quot;Times New Roman&quot;"><span style="mso-list:Ignore">1.<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-size:14.0pt;font-family:宋体;mso-ascii-font-family:&quot;Times New Roman&quot;;
mso-hansi-font-family:&quot;Times New Roman&quot;">接口设计</span><span lang="EN-US" style="font-size:14.0pt"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-left:24.75pt;text-indent:-24.75pt;mso-list:
l0 level2 lfo1;tab-stops:list 24.75pt"><span lang="EN-US" style="font-size:14.0pt;mso-fareast-font-family:&quot;Times New Roman&quot;"><span style="mso-list:Ignore">1.1<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;
</span></span></span><span style="font-size:14.0pt;font-family:宋体;
mso-ascii-font-family:&quot;Times New Roman&quot;;mso-hansi-font-family:&quot;Times New Roman&quot;">外部接口设计</span><span lang="EN-US" style="font-size:14.0pt"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-left:24.75pt"><span style="font-size:14.0pt;
font-family:宋体;mso-ascii-font-family:&quot;Times New Roman&quot;;mso-hansi-font-family:
&quot;Times New Roman&quot;">由于微信小程序基于腾讯云端服务器，所以硬件接口不在讨论范围内，这里主要讨论软件接口：</span><span lang="EN-US" style="font-size:14.0pt"><o:p></o:p></span></p>


接口类型 | 接口 | 功能说明
-- | -- | --
调用本地接口 | 系统拍照和图库功能 | 用于用户上传图片至云端服务器进行分析
调用云端接口 | 小程序云端数据库接口 | 用于存储用户数据，用户识别历史数据等



<p class="MsoNormal" style="margin-left:24.75pt;text-indent:-24.75pt;mso-list:
l0 level2 lfo1;tab-stops:list 24.75pt"><span lang="EN-US" style="font-size:14.0pt;mso-fareast-font-family:&quot;Times New Roman&quot;"><span style="mso-list:Ignore">1.2<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;
</span></span></span><span style="font-size:14.0pt;font-family:宋体;
mso-ascii-font-family:&quot;Times New Roman&quot;;mso-hansi-font-family:&quot;Times New Roman&quot;">内部接口设计</span><span lang="EN-US" style="font-size:14.0pt"><o:p></o:p></span></p>


接口说明 | 操作
-- | --
本地小程序端 | 服务器端
上传图片 | 将图片信息传送至服务器 | 接收图片信息，进行目标检测和识别
接收识别结果 | 接收识别结果并呈现 | 将识别结果返回至小程序端
发送查询识别历史信息请求 | 将查询请求发送至服务器端 | 根据请求进行查询
接收识别历史信息数据 | 接收历史识别信息的数据 | 将查询结果返回至小程序端



<p class="MsoNormal" style="margin-left:24.75pt;text-indent:-24.75pt;mso-list:
l0 level2 lfo1;tab-stops:list 24.75pt"><span lang="EN-US" style="font-size:14.0pt;mso-fareast-font-family:&quot;Times New Roman&quot;"><span style="mso-list:Ignore">1.3<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;
</span></span></span><span style="font-size:14.0pt;font-family:宋体;
mso-ascii-font-family:&quot;Times New Roman&quot;;mso-hansi-font-family:&quot;Times New Roman&quot;">人机接口设计</span><span lang="EN-US" style="font-size:14.0pt"><o:p></o:p></span></p>


接口描述 | 用户请求 | 小程序应答
-- | -- | --
上传图片 | 请求系统调用图库或者相机 | 弹出请求窗口，经过允许后打开相机或是图库
请求历史识别记录 | 请求查看历史记录 | 切换历史记录页面，进行历史识别记录的显示



<p class="MsoNormal" style="margin-left:24.75pt"><span lang="EN-US" style="font-size:14.0pt"><o:p>&nbsp;</o:p></span></p>
