### ISSUE TITLE
开发计划书1、3部分编写

### ISSUE THREAD

**Issue by hanhun7** [hanhun7/InsectIdentify#6]

**Comment by lemonanaaa** [comment]
引言
1.1 编写目的
本项目计划书文档主要反映出林业有害生物智能识别系统的具体计划方案，引导软件开发人员进行后续的开发工作。此项目计划文档既可以作为软件开发工作的基础和依据，也可以作为此项目确认测试和验收的凭照，以便于保证项目团队按时保质地完成项目目标，便于项目团队成员更好地了解项目情况，使项目工作开展的各个过程合理有序。
本文档预期面向多种读者： 
（1）项目经理：项目经理可以根据该文档了解预期物品的功能设计，并据此进行项目管理。 
（2）程序员：程序员可以配合需求规格说明书和此项目设计文档，了解所需要进行开发的功能，进行代码的编写。 
（3）测试员：测试员可以根据需求规格说明书和此项目设计报告编写测试用例，并对系统进行功能性测试和非功能性测试。 
（4）产品经理：产品经理可以根据需求规格说明书、此项目设计报告和开发出来的系统代码，撰写用户手册。 
（5）其他人员：其他人员如部门领导、公司领导等可以据此了解系统的功能设计。
1.2 背景
在我国社会经济快速发展的背景下，生态保护越来越重要，而林业有害生物防治工作在推动林业的可持续发展方面有非常重要的作用。
根据软件项目管理课程要求，本项目致力于通过图像识别进行智能分析，从而对林业有害生物进行侦查来促进林业生态环境建设。
1.3 定义
1)	人工智能：是研究、开发用于模拟、延伸和扩展人的智能的理论、方法、技术及应用系统的一门新的技术科学。 
2)	balabala
1.4 参考资料
【待定】 
软件开发标准引用
1)	GB／T 8567-2006 计算机软件文档编制规范
1.5 标准、条约和约定
标准、条约和约定：
1)	GB／T 8567-2006 计算机软件文档编制规范






<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel="Edit-Time-Data" href="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel="themeData" href="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>






<h2><span style="mso-spacerun:yes">&nbsp;</span><span style="font-family:方正黑体_GBK;
mso-ascii-font-family:&quot;DejaVu Sans&quot;">项目团队组织</span><span lang="EN-US"><o:p></o:p></span></h2>

<h3><a name="_Toc45397047_WPSOffice_Level2"><span lang="EN-US">3.1 </span></a><span style="mso-bookmark:_Toc45397047_WPSOffice_Level2"><span style="font-family:
宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin">组织结构</span></span><span lang="EN-US"><o:p></o:p></span></h3>

<p class="MsoNormal" style="text-indent:21.0pt;mso-char-indent-count:2.0"><span style="font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin">为完成本项目任务，将团队组织为：项目经理，设计和编码，测试三个组，三个组的团队成员都有交叉。</span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal" align="center" style="text-align:center"><span lang="EN-US" style="mso-no-proof:yes"><img width="485" height="210" src="file:///C:/Users/lemon/AppData/Local/Temp/msohtmlclip1/01/clip_image002.gif" v:shapes="图片_x0020_3"></span><span lang="EN-US"><o:p></o:p></span></p>

<h3><a name="_Toc631474244_WPSOffice_Level2"><span lang="EN-US">3.2 </span></a><span style="mso-bookmark:_Toc631474244_WPSOffice_Level2"><span style="font-family:
宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin">人员分工</span></span><span lang="EN-US"><o:p></o:p></span></h3>

<div align="center">


姓名 | 角色 | 工作描述
-- | -- | --
王心雨 | 项目管理，前期分析，设计 | 分析系统需求，项目计划，项目团队管理，进度把握
王璐瑶 | 分析，设计，编码，文档编写 | 分析需求，代码模块编写，软件使用手册编写
李萌 | 设计，编码，文档编写，测试 | 代码模块编写，软件使用手册编写，软件测试
刘桐源 | 分析，设计，编码，测试 | 需求分析，代码模块编写，软件测试



</div>

<p class="MsoNormal" align="left" style="text-align:left;mso-pagination:widow-orphan"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><a name="_Toc323435434_WPSOffice_Level2"><span lang="EN-US">3.3 </span></a><span style="mso-bookmark:_Toc323435434_WPSOffice_Level2"><span style="font-family:
宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin">协作与沟通</span></span><span lang="EN-US"><o:p></o:p></span></h3>

<p class="MsoNormal"><span style="font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-theme-font:minor-fareast;
mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin">本项目为课程作业项目，因此以下只列出项目团队内部协作。</span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>


沟通对象 | 团队内部成员，包括项目经理，设计和编码组，测试组所有成员
-- | --
沟通方式 | 通过面对面会议，腾讯会议（网络），QQ聊天群和私聊方式开展沟通活动
协作模式 | 团队在不同时期有不同的分工，其中项目经理为王心雨同学担任，在设计阶段王璐瑶和刘桐源同学为设计和编码组成员，在编码阶段王璐瑶，李萌和刘桐源同学都为设计和编码组成员，在测试阶段团队所有成员都参与软件测试，由于团队人数较少，因此设计为扁平化管理
沟通内容 | 沟通内容包括角色临时分配，项目阶段现状沟通，测试内容沟通等
